// <auto-generated />
namespace Project_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class managersdepartments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(managersdepartments));
        
        string IMigrationMetadata.Id
        {
            get { return "202302191844554_managers-departments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
